### ISSUE TITLE
Multi-release jar support

### ISSUE THREAD

**Issue by FroMage** [arquillian/arquillian-core#212]
Multi-release jar breaks arquillian.

I got this exception using Arquillian with an MR-jar:

```
java.lang.NoClassDefFoundError: io/smallrye/context/Jdk9CompletableFutureWrapper (wrong name: META-INF/versions/9/io/smallrye/context/Jdk9CompletableFutureWrapper)
...
    at org.jboss.arquillian.container.weld.embedded.Utils.filterClasses(Utils.java:182)
    at org.jboss.arquillian.container.weld.embedded.Utils.findBeanClasses(Utils.java:149)
    at org.jboss.arquillian.container.weld.embedded.WeldMockContainer.deploy(WeldMockContainer.java:109)
    at org.jboss.arquillian.container.impl.client.container.ContainerDeployController$3.call(ContainerDeployController.java:151)
    at org.jboss.arquillian.container.impl.client.container.ContainerDeployController$3.call(ContainerDeployController.java:118)
    at org.jboss.arquillian.container.impl.client.container.ContainerDeployController.executeOperation(ContainerDeployController.java:239)
    at org.jboss.arquillian.container.impl.client.container.ContainerDeployController.deploy(ContainerDeployController.java:118)
```

Looks at the source code in question, I was able to add a `beans.xml` to avoid scanning those classes as a workaround:

```Stephane Epardaud:
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://java.sun.com/xml/ns/javaee"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:weld="http://jboss.org/schema/weld/beans"
       xsi:schemaLocation="
          http://java.sun.com/xml/ns/javaee http://docs.jboss.org/cdi/beans_1_0.xsd
          http://jboss.org/schema/weld/beans http://jboss.org/schema/weld/beans_1_1.xsd">
    <weld:scan>
        <!-- Don't let Arquillian choke on MR-Jars -->
        <weld:exclude weld:pattern="META-INF\.versions\..*"></weld:exclude>
    </weld:scan>
</beans>
Stephane Epardaud: and it passes the fucking TCK now

```xml
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://java.sun.com/xml/ns/javaee"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:weld="http://jboss.org/schema/weld/beans"
       xsi:schemaLocation="
          http://java.sun.com/xml/ns/javaee http://docs.jboss.org/cdi/beans_1_0.xsd
          http://jboss.org/schema/weld/beans http://jboss.org/schema/weld/beans_1_1.xsd">
    <weld:scan>
        <!-- Don't let Arquillian choke on MR-Jars -->
        <weld:exclude weld:pattern="META-INF\.versions\..*"></weld:exclude>
    </weld:scan>
</beans>
```

**Comment by bartoszmajsak** [comment]
By looking at the stacktrace I just wonder if that is an Arquillian Core or perhaps weld-container-adapter? What's the code in question you are referring to?

**Comment by FroMage** [comment]
I think it's `org.jboss.arquillian.container.weld.embedded.Utils.filterClasses`, did I file in the wrong project? Which one should I file on? Can we move the issue or do I need to reopen one?
Thanks.

**Comment by bartoszmajsak** [comment]
No worries, I will take care of it.

**Comment by FroMage** [comment]
Thanks.
