### ISSUE TITLE
No command response within timeout of 30000 ms.

### ISSUE THREAD

**Issue by miPlodder** [arquillian/arquillian-core#483]
When I execute below mentioned command with 2 profiles `jacoco` and `integration-test`, I see integration tests runs successfully. whereas Jacoco profile fails.

> mvn -T4 clean install -P docker -D skipTests && mvn -pl com.princetonecom.clientconsole:clientconsole-test verify -P jacoco,integration-test

<h3>Logs</h3>

```
java.lang.RuntimeException: Could not run @AfterSuite
	at test-SNAPSHOT.ear//org.jboss.arquillian.junit.AdaptorManager.shutdown(AdaptorManager.java:53)
	at test.ear//org.jboss.arquillian.junit.AdaptorManagerWithNotifier$1.testRunFinished(AdaptorManagerWithNotifier.java:29)
	at test-SNAPSHOT.ear//org.junit.runner.notification.SynchronizedRunListener.testRunFinished(SynchronizedRunListener.java:42)
	at test-SNAPSHOT.ear//org.junit.runner.notification.RunNotifier$2.notifyListener(RunNotifier.java:103)
	at test-SNAPSHOT.ear//org.junit.runner.notification.RunNotifier$SafeNotifier.run(RunNotifier.java:72)
	at test-SNAPSHOT.ear//org.junit.runner.notification.RunNotifier.fireTestRunFinished(RunNotifier.java:100)
	at test-SNAPSHOT.ear//org.junit.runner.JUnitCore.run(JUnitCore.java:138)
	at test-SNAPSHOT.ear//org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at test-SNAPSHOT.ear//org.jboss.arquillian.junit.container.JUnitTestRunner.execute(JUnitTestRunner.java:61)
	at test-SNAPSHOT.ear//org.jboss.arquillian.protocol.servlet.runner.ServletTestRunner.executeTest(ServletTestRunner.java:139)
	at test-SNAPSHOT-war.war//org.jboss.arquillian.protocol.servlet.runner.ServletTestRunner.execute(ServletTestRunner.java:117)
	at test-SNAPSHOT-war.war//org.jboss.arquillian.protocol.servlet.runner.ServletTestRunner.doGet(ServletTestRunner.java:86)
	at javax.servlet.api@2.0.0.Final//javax.servlet.http.HttpServlet.service(HttpServlet.java:503)
	at javax.servlet.api@2.0.0.Final//javax.servlet.http.HttpServlet.service(HttpServlet.java:590)
	at io.undertow.servlet@2.2.19.Final//io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
	at o.undertow.servlet@2.2.19.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
...
org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
	at org.jboss.xnio@3.8.7.Final//org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1282)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.RuntimeException: No command response within timeout of 30000 ms.
	at test-SNAPSHOT.ear-war.war//org.jboss.arquillian.protocol.servlet.runner.ServletCommandService.execute(ServletCommandService.java:54)
	at test-SNAPSHOT.ear//org.jboss.arquillian.extension.jacoco.container.ShutdownCoverageData.writeCoverageData(ShutdownCoverageData.java:63)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at test-SNAPSHOT.ear//org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
	at test-SNAPSHOT.ear//org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:103)
	at test-SNAPSHOT.ear//org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:90)
	at test-SNAPSHOT.ear//org.jboss.arquillian.test.impl.TestContextHandler.createSuiteContext(TestContextHandler.java:69)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at test-SNAPSHOT.ear//org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
	at test-SNAPSHOT.ear//org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:95)
	at test-SNAPSHOT.ear//org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:133)
	at test-SNAPSHOT.ear//org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:105)
	at test-SNAPSHOT.ear//org.jboss.arquillian.test.impl.EventTestRunnerAdaptor.afterSuite(EventTestRunnerAdaptor.java:75)
	at test-SNAPSHOT.ear//org.jboss.arquillian.junit.AdaptorManager.shutdown(AdaptorManager.java:44)
	... 90 more
```

**Comment by starksm64** [comment]
I can't say it is a known issue. Do you have an example project repo that illustrates this?
