### ISSUE TITLE
Upgrade of RestEasy to 6.2.6.Final requires jakarta.ws.rs-api 3.1.0

### ISSUE THREAD

**Issue by starksm64** [arquillian/arquillian-core#514]
While looking at why the dependabot upgrade of RestEasy to 6.2.6.Final was failing the CI tests, I found the following execption showing up in the Jetty output (once configured correctly):

```java
java.lang.ClassNotFoundException: jakarta.ws.rs.core.NewCookie$SameSite
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:527)
	at org.jboss.resteasy.core.providerfactory.ResteasyProviderFactoryImpl.initializeCommon(ResteasyProviderFactoryImpl.java:244)
	at org.jboss.resteasy.core.providerfactory.ResteasyProviderFactoryImpl.initialize(ResteasyProviderFactoryImpl.java:281)
	at org.jboss.resteasy.core.providerfactory.ResteasyProviderFactoryImpl.<init>(ResteasyProviderFactoryImpl.java:155)
	at org.jboss.resteasy.core.ResteasyDeploymentImpl.initializeFactory(ResteasyDeploymentImpl.java:290)
	at org.jboss.resteasy.core.ResteasyDeploymentImpl.startInternal(ResteasyDeploymentImpl.java:131)
	at org.jboss.resteasy.core.ResteasyDeploymentImpl.start(ResteasyDeploymentImpl.java:124)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.init(ServletContainerDispatcher.java:134)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.init(HttpServletDispatcher.java:39)
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:633)
	at org.eclipse.jetty.servlet.ServletHolder.getServlet(ServletHolder.java:486)
	at org.eclipse.jetty.servlet.ServletHolder.prepare(ServletHolder.java:731)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:524)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1570)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1382)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1543)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1304)
```

This version of RestEasy has updated the  jakarta.ws.rs-api to 3.1.0 and is using new classes from the version whcih makes the current usage of 3.0.0 fail.

We also need to update the configuration of Jetty in the test module to property log output as this failure was not seen in the CI run logs.

**Comment by starksm64** [comment]
This has been done in the new https://github.com/arquillian/arquillian-jakarta repo
